package cn.soft.zhaopin.base.pojo.po;

public class B{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b.a
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    private String a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b.b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    private String b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b.c
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    private String c;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b.d
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    private String d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b.e
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    private String e;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b.a
     *
     * @return the value of b.a
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b.a
     *
     * @param a the value for b.a
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    public void setA(String a) {
        this.a = a == null ? null : a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b.b
     *
     * @return the value of b.b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b.b
     *
     * @param b the value for b.b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    public void setB(String b) {
        this.b = b == null ? null : b.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b.c
     *
     * @return the value of b.c
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    public String getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b.c
     *
     * @param c the value for b.c
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    public void setC(String c) {
        this.c = c == null ? null : c.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b.d
     *
     * @return the value of b.d
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b.d
     *
     * @param d the value for b.d
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    public void setD(String d) {
        this.d = d == null ? null : d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b.e
     *
     * @return the value of b.e
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    public String getE() {
        return e;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b.e
     *
     * @param e the value for b.e
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    public void setE(String e) {
        this.e = e == null ? null : e.trim();
    }

    @Override
    public String toString() {
        return "B{" +
                "a='" + a + '\'' +
                ", b='" + b + '\'' +
                ", c='" + c + '\'' +
                ", d='" + d + '\'' +
                ", e='" + e + '\'' +
                '}';
    }
}