package cn.soft.zhaopin.base.pojo.po;

public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private Integer jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_name
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_nickName
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private String jobNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private Integer jobGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_level
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private Integer jobLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_id
     *
     * @return the value of job.job_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_id
     *
     * @param jobId the value for job.job_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_name
     *
     * @return the value of job.job_name
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_name
     *
     * @param jobName the value for job.job_name
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_nickName
     *
     * @return the value of job.job_nickName
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public String getJobNickname() {
        return jobNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_nickName
     *
     * @param jobNickname the value for job.job_nickName
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setJobNickname(String jobNickname) {
        this.jobNickname = jobNickname == null ? null : jobNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_group_id
     *
     * @return the value of job.job_group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public Integer getJobGroupId() {
        return jobGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_group_id
     *
     * @param jobGroupId the value for job.job_group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setJobGroupId(Integer jobGroupId) {
        this.jobGroupId = jobGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_level
     *
     * @return the value of job.job_level
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public Integer getJobLevel() {
        return jobLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_level
     *
     * @param jobLevel the value for job.job_level
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setJobLevel(Integer jobLevel) {
        this.jobLevel = jobLevel;
    }
}