package cn.soft.zhaopin.base.pojo.po;

public class JobGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_group.group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_group.goup_name
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private String goupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_group.main_group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private Integer mainGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_group.group_detail
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private String groupDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_group.group_other
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private String groupOther;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_group.group_id
     *
     * @return the value of job_group.group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_group.group_id
     *
     * @param groupId the value for job_group.group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_group.goup_name
     *
     * @return the value of job_group.goup_name
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public String getGoupName() {
        return goupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_group.goup_name
     *
     * @param goupName the value for job_group.goup_name
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setGoupName(String goupName) {
        this.goupName = goupName == null ? null : goupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_group.main_group_id
     *
     * @return the value of job_group.main_group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public Integer getMainGroupId() {
        return mainGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_group.main_group_id
     *
     * @param mainGroupId the value for job_group.main_group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setMainGroupId(Integer mainGroupId) {
        this.mainGroupId = mainGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_group.group_detail
     *
     * @return the value of job_group.group_detail
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public String getGroupDetail() {
        return groupDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_group.group_detail
     *
     * @param groupDetail the value for job_group.group_detail
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setGroupDetail(String groupDetail) {
        this.groupDetail = groupDetail == null ? null : groupDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_group.group_other
     *
     * @return the value of job_group.group_other
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public String getGroupOther() {
        return groupOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_group.group_other
     *
     * @param groupOther the value for job_group.group_other
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setGroupOther(String groupOther) {
        this.groupOther = groupOther == null ? null : groupOther.trim();
    }
}