package cn.soft.zhaopin.base.pojo.po;

public class MainGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_group.main_group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private Integer mainGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column main_group.main_group_name
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    private String mainGroupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_group.main_group_id
     *
     * @return the value of main_group.main_group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public Integer getMainGroupId() {
        return mainGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_group.main_group_id
     *
     * @param mainGroupId the value for main_group.main_group_id
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setMainGroupId(Integer mainGroupId) {
        this.mainGroupId = mainGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column main_group.main_group_name
     *
     * @return the value of main_group.main_group_name
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public String getMainGroupName() {
        return mainGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column main_group.main_group_name
     *
     * @param mainGroupName the value for main_group.main_group_name
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    public void setMainGroupName(String mainGroupName) {
        this.mainGroupName = mainGroupName == null ? null : mainGroupName.trim();
    }
}