package cn.soft.zhaopin.base.mapper;

import cn.soft.zhaopin.base.pojo.po.B;
import cn.soft.zhaopin.base.pojo.po.BExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    long countByExample(BExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    int deleteByExample(BExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    int deleteByPrimaryKey(String a);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    int insert(B record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    int insertSelective(B record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    List<B> selectByExample(BExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    B selectByPrimaryKey(String a);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") B record, @Param("example") BExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    int updateByExample(@Param("record") B record, @Param("example") BExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    int updateByPrimaryKeySelective(B record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated Fri Aug 31 17:11:18 CST 2018
     */
    int updateByPrimaryKey(B record);
}