package cn.soft.zhaopin.base.mapper;

import cn.soft.zhaopin.base.pojo.po.JobGroup;
import cn.soft.zhaopin.base.pojo.po.JobGroupExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JobGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    long countByExample(JobGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int deleteByExample(JobGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int insert(JobGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int insertSelective(JobGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    List<JobGroup> selectByExample(JobGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    JobGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") JobGroup record, @Param("example") JobGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByExample(@Param("record") JobGroup record, @Param("example") JobGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByPrimaryKeySelective(JobGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByPrimaryKey(JobGroup record);
}