package cn.soft.zhaopin.base.mapper;

import cn.soft.zhaopin.base.pojo.po.Job;
import cn.soft.zhaopin.base.pojo.po.JobExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    long countByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int deleteByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int deleteByPrimaryKey(Integer jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    List<Job> selectByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    Job selectByPrimaryKey(Integer jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByExample(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByPrimaryKey(Job record);
}