package cn.soft.zhaopin.base.mapper;

import cn.soft.zhaopin.base.pojo.po.MainGroup;
import cn.soft.zhaopin.base.pojo.po.MainGroupExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MainGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    long countByExample(MainGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int deleteByExample(MainGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int deleteByPrimaryKey(Integer mainGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int insert(MainGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int insertSelective(MainGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    List<MainGroup> selectByExample(MainGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    MainGroup selectByPrimaryKey(Integer mainGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") MainGroup record, @Param("example") MainGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByExample(@Param("record") MainGroup record, @Param("example") MainGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByPrimaryKeySelective(MainGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_group
     *
     * @mbg.generated Mon Sep 03 17:24:50 CST 2018
     */
    int updateByPrimaryKey(MainGroup record);
}